### ISSUE TITLE
out_dir not defined error

### ISSUE THREAD

**Issue by MayankMurali** [splicebox/Jutils#5]
Hi @edwwlui,

Was trying to use your wonderful tool. I think after you recent commit ([f07aab8](https://github.com/splicebox/Jutils/commit/f07aab8406a2f6c14f6fd7240af8d49f2c1d6f45)), the --out-dir is no longer defined within the `run_convert_results_module`'s scope, hence leading to this error which I am getting:

> jutils.py", line 84, in run_convert_results_module
>     convert_rmats_results(Path(args.rmats_dir), out_dir)
> NameError: name 'out_dir' is not defined

**Comment by edwwlui** [comment]
Thank you @MayankMurali for using Jutils and reporting this! Fixed it, please let me know if any more issues.
