### ISSUE TITLE
[heatmap] plot only user provided genes / events

### ISSUE THREAD

**Issue by adomingues** [splicebox/Jutils#6]
Hi @edwwlui ,

thank you for the tool - pretty useful. I have one feature request (question):

Is it possible to create an heatmap displaying genes or events provided by the user? Quite often I have a list of genes of interest and I just want to plot changes in those.

Cheers.

**Comment by adomingues** [comment]
@Guangyu-Yang another small request, is if it's possible to place the heatmap legend in another position. In a my run it occupies a lot of space at the top, which is less than ideal:

![image](https://github.com/splicebox/Jutils/assets/2607577/fbd02f7a-a53d-473d-bb25-cc3b9cef6bba)

 The sample cluster tree also seems oversized. It was run with:

```bash
python3 ${jutils} heatmap --tsv-file ${outdir_stat}/jutils/rmats_JCEC_results.tsv --meta-file ${outdir_stat}/jutils/meta.tsv --dpsi 0.1  --q-value 0.05 --method 'weighted' --metric 'cityblock' --pdf --out-dir ${outdir_stat}/jutils/figure --prefix "DMSO-WT"
```

But it's a similar picture if ran with `--unsupervised`. The version is latest commit, f9e22262.

Cheers.

**Comment by edwwlui** [comment]
Thank you @adomingues for using Jutils, we are working towards the solutions!

**Comment by edwwlui** [comment]
Both features have been implemented, please have a try and let us know if you have any questions!

**Comment by adomingues** [comment]
Thanks @edwwlui I will check it out during the week.

**Comment by guptas2005** [comment]
Hello @edwwlui, where are these options available to customize? I'm looking specifically at the heatmap's ability to look at genes of interest.
