### ISSUE TITLE
Genomic position are truncated in shashimi plot

### ISSUE THREAD

**Issue by Benoitdw** [splicebox/Jutils#8]
Hello, 
Genomic position are truncated (without bam) 
![image](https://github.com/user-attachments/assets/c7a84308-dd44-4b03-b42e-5550ecdf3103)
I fixed it by adding +1 in sashimi_utils.py line 107 :
` height, width, base_size = 3 * len(overlay_dict), 10, 14 `
->
`height, width, base_size = 3 * len(overlay_dict) +1 , 10, 14`

Now we can see the genomic position 
![image](https://github.com/user-attachments/assets/adcda055-b37d-48e8-bc03-6b6d0ea72c50)

This is my command line with 3 control and 1 normal 
```bash
python jutils.py sashimi \
    --meta-file meta.tsv \
    --tsv-file out/rmats_JCEC_results.tsv \
    --group-id J00590 \
    --gtf gtf.gtf
```

**Comment by edwwlui** [comment]
Hi Benoitdw,

Thanks for using jutils and catching that issue! Your change has been applied. Please let me know if you encounter any further issues.
